### ISSUE TITLE
After the first script execution, script doesn't work anymore (cronjob)

### ISSUE THREAD

**Issue by VladimirMikulic** [RaitaroH/KDE-Terminal-Wallpaper-Changer#1]
As the title says, when I run the script for the first time, it works fine, but after the first time script doesn't work anymore. Why is it so hard to change desktop wallpaper via CLI on KDE?

**Comment by edeetee** [comment]
Yep I've got the same issue. :(

**Comment by edeetee** [comment]
I'll add that it does seem to set the wallpaper, just not trigger an update, as after immediately reboot the wallpaper has been changed.

**Comment by RaitaroH** [comment]
@VladimirMikulic @edeetee Not sure what you mean actually. Can you try:
```
ksetwallpaper image.png
```
and see if that works? I have also updated the script and readme to make it easier to understand.

**Comment by edeetee** [comment]
Okay after some more testing, it seems to be related to me running inside a cron job, as otherwise it works flawlessly.

**Comment by RaitaroH** [comment]
@edeetee thank you. I have changed the name of the issue a bit so further issues will not be created.
I have never actually used the script in a cronjob before, so I never noticed. I personally just call the script from sxhkd keybindings.
